Fixed and added cp params
marlinprotocol/marlinctl2 pull request #21
Opened 2023-07-04 07:31 UTC by nisarg-soni

- Added cp params for bandwidth rates, contract address, provider address, whitelisted addresses, blacklisted addresses
- fixed params for blacklist and whitelist

2023-07-12 07:07 UTC, roshanrags requested changes
Name things properly everywhere.

2023-07-12 07:07 UTC, roshanr95 commented on cmd/cp/cp.go
>  	app.CreateCmd.ArgStore["rates"] = app.CreateCmd.Cmd.Flags().StringP("rates", "t", "", "Location of rates for instance types")
`instance-rates`

2023-07-12 07:07 UTC, roshanr95 commented on cmd/cp/cp.go
>  	app.CreateCmd.ArgStore["white"] = app.CreateCmd.Cmd.Flags().StringP("white", "w", "", "Location of whitelist file")
`image-whitelist`

2023-07-16 08:32 UTC, nisarg-soni commented
> Name things properly everywhere.

All resolved

2023-07-17 06:53 UTC, roshanr95 approved these changes

2023-07-17 06:54 UTC, merged